### ISSUE TITLE
Delete unnecessary files from github

### ISSUE THREAD

**Issue by EiseleA** [MAST-ULiege/OmexdiaCalibrationPackage#2]
like NOAH_Data, Load_NOAH_Data.Rmd, HammondFl2, Ham_Fluxes, Ham_Profiles, Ham_Stations, Hammond_Load, MinimalRun, MinimalRun_NOAH

**Comment by acapet** [comment]
Done. Any obsolete file left ?

**Comment by EiseleA** [comment]
Don´t know if the MinimalRuns are still necessary? Arent they included in the CalibrationProcedure anyway?



-----Arthur Capet <notifications@github.com> schrieb: -----

An: acapet/OmexdiaCalibrationPackage <OmexdiaCalibrationPackage@noreply.github.com>
Von: Arthur Capet <notifications@github.com>
Datum: 27.10.2017 14:45
Kopie: EiseleA <annika.eisele@hzg.de>, Author <author@noreply.github.com>
Betreff: Re: [acapet/OmexdiaCalibrationPackage] Delete unnecessary files from github (#2)


Done. Any obsolete file left ?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.


 
Helmholtz-Zentrum Geesthacht 
Zentrum für Material- und Küstenforschung GmbH 
Max-Planck-Straße 1 I 21502 Geesthacht I Deutschland/Germany 

Geschäftsführer/Board of Management: Prof. Dr. Wolfgang Kaysser, Dipl.-Ing. Michael Ganß 
Vorsitzender des Aufsichtsrates/Chairman of the Supervisory Board: Ministerialdirigent Dr. Herbert Zeisel 
Amtsgericht Lübeck HRB 285 GE (Register Court) 
Internet: http://www.hzg.de

**Comment by acapet** [comment]
I'm currently cleaning one (using the HAMMOND data you prepared) as a quick and easy example.

**Comment by acapet** [comment]
In this regard, I'm turning data load as a function ( with the file given in argument, + argument plotting and mapping set as default FALSE)
