### ISSUE TITLE
generalize ObsAtSta

### ISSUE THREAD

**Issue by EiseleA** [MAST-ULiege/OmexdiaCalibrationPackage#3]
Current version of ObsAtSta is very specific to the data. A generalized format would be nice.
Very helpful in this respect would be also to include an automatic mechanism checking for variable names corresponding and/or translating to model parameters. 
Also an automatic checkup if an error is given in the Excel-Files could be useful and how to proceed with the data when now error is given (like implementing an artificial error?)

**Comment by acapet** [comment]
Let stick to the following rules : Column names in the "Profiles" sheet should
* correspond directly to model variables (in terms of title but then also unit and definition) 
* Have a correponding function in the user-defined function .r file.

Then the automatic check can be done by the generic load function.

Regarding automatic name replacement .. I'm not sure . 

Regarding automatic error ... We could put a default 10% error , but this is something user will abused of.

**Comment by acapet** [comment]
I added functions for Diagnostic Observations (those not defined as a state variables) in UserDefinitions_HAMMOND.R for 

* TOC
* TN
* Sidet

**Comment by acapet** [comment]
Also, OmexCal_LoadDat.R set default 30% error when none is given.
