### ISSUE TITLE
Adding different cruises and stations

### ISSUE THREAD

**Issue by EiseleA** [MAST-ULiege/OmexdiaCalibrationPackage#9]
Fine-tuning the calibration procedure when Accounting for different stations and Cruises. Maybe implement a ranking by which basis/criteria the calibration should be proceeded.

**Comment by acapet** [comment]
By fine tuning, do you mean to use different user configuration? 

In that case I would write different user file and run the calibration procedure for a set of stations/campaign using the specific user file. 

This being said, one aspect that user may want to fine tune is the starting value, and valid range given for parameters. For now, this is set as general and not user-specific. 

The ranking may be handled (if i understand your point correctly) by changing errors associated with observations in the data file, which makes it station/campaign specific.
